### PR TITLE
Applied formatting to most files

### PR DESCRIPTION
**Pull request by JelleInfinity**
If something is not to your liking, I can see if there is a setting I can change

### CODE REVIEW

**Comment by LuqueDaniel** [comment]
I'll review it, although I'm not very familiar with TypeScript code conventions and style guide. As long as it's close to what is generally considered standard in TypeScript it should be fine.

**Comment by JelleInfinity** [comment]
This is using that Prettier plugin to format the documents. I assume they apply the formatting defaults to what they consider standard

**Review by LuqueDaniel — APPROVED** [review]
LGTM! 🎉

**Comment by JelleInfinity** [comment]
@LuqueDaniel I fixed the merge conflict. You should be able to merge it now

**Pull request merged**
