### PR TITLE
Draft: First check if a key already exists

### PR DESCRIPTION
**Pull request by duckdoom4**
@LuqueDaniel I wrote this code on my phone with GitHub codespaces, so I couldn't test this. Also the nodejs 'util' module still requires an import.

So if you can, please check if it works. I'd do it myself, but I won't be near my pc for the following week. 🙃

Also, I want to add another custom container 'HashSet' for this. That'll be a much more efficient way to perform this action. But for now this will suffice

### CODE REVIEW

**Comment by duckdoom4** [comment]
Oh btw, looking at the error output of the formatting check. Are you able to change some settings to make it output what is actually wrong with the formatting instead of 'run prettier on this file'? Cus now I'm not sure how to fix it

**Comment by LuqueDaniel** [comment]
@duckdoom4 Thanks. When I get home I'll check it :)

**Comment by duckdoom4** [comment]
Actually about that, IIRC at some point I thought I switched from prettier's formatting to ESLint. 
Should probably have a look at that at some point, since that would mean we can remove one dependency.

I think prettier was quite heavy on the startup time. Adding like half a second if not more.

**Comment by LuqueDaniel** [comment]
It seems that Prettier doesn't have the option to display file formatting errors. `--check` only shows the error "[warn] Code style issues found in the above file. Forgot to run Prettier?". I think the formatting error is because it uses 2 spaces instead of 4 for indentation.

**Comment by duckdoom4** [comment]
Ah, okay. Well maybe ESLint will be better. We can have a look later.

I think I wanted to use that, because it had more freedom in the formatting preferences then prettier

**Comment by LuqueDaniel** [comment]
@duckdoom4 From which module should I import `util`? Also, can you tell me the behavior to test?

**Comment by duckdoom4** [comment]
It's this one:
(But there it's using the js require)
https://www.geeksforgeeks.org/node-js-util-isdeepstrictequal-method/

**Comment by LuqueDaniel** [comment]
I've checked, and duplicate entries are not added... Although I can't duplicate them in the `develop` branch either.

**Comment by duckdoom4** [comment]
Hmm, I'm not sure what would trigger it to be added multiple times.. 
But from reading the code I can tell that it was certainly possible and that this would fix it.

I suggest we make a new patch release with this code added and ask that person if it fixed his issue.

**Review by LuqueDaniel — APPROVED** [review]
Looks great to me!

**Comment by LuqueDaniel** [comment]
> Hmm, I'm not sure what would trigger it to be added multiple times.. But from reading the code I can tell that it was certainly possible and that this would fix it.
> 
> I suggest we make a new patch release with this code added and ask @FaceCrap if it fixed his issue.

Do we publish the release or just compile the extension?

**Comment by duckdoom4** [comment]
I think it's safe to publish if it's still working

**Pull request merged**
