### PR TITLE
Add Python-like custom folding markers.

### PR DESCRIPTION
**Pull request by joe69-96**

### CODE REVIEW

**Comment by LuqueDaniel** [comment]
@joe69-96 Thanks for the PR!

Can you add the `offSide` setting and test if it works fine with Ren'Py code? More information: https://github.com/Microsoft/vscode/issues/3353#issuecomment-330797736

**Comment by joe69-96** [comment]
It does work as expected and, in fact, fixes one of the issues I had with folding in the first place.

**Comment by joe69-96** [comment]
> @joe69-96 Thanks for the PR!
> 
> Can you add the `offSide` setting and test if it works fine with Ren'Py code? More information: [microsoft/vscode#3353 (comment)](https://github.com/microsoft/vscode/issues/3353#issuecomment-330797736)

It does work as expected and, in fact, fixes one of the issues I had with folding in the first place.

**Comment by LuqueDaniel** [comment]
Thanks!

**Pull request merged**
