### PR TITLE
Fix: branch reset group seems to not work

### PR DESCRIPTION
**Pull request by JelleInfinity**
This fixes broken strings

### CODE REVIEW

**Comment by LuqueDaniel** [comment]
No changes in the commit?

**Comment by JelleInfinity** [comment]
Lol wait what? 😂

**Comment by JelleInfinity** [comment]
Ah, I see what happened. I added this change to a branch, forgot I added it there and assumed this was on the main branch.

This was never on here, so nothing to fix. Sorry about that 😅

**Comment by LuqueDaniel** [comment]
Don't worry! 👍

**Pull request closed without merging**
